INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('CameloManco', 1, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Itau Old', 1, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Itaú', 1, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Real', 1, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('American Express', 4, 1, 20, NULL, 5000.0000);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Diners', 4, 1, 20, NULL, 3800.0000);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('MasterCard Unibanco', 4, 1, 20, NULL, 9800.0000);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Real Visa', 4, 1, 20, NULL, 1000.0000);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Visa AAdvantage', 4, 1, 20, NULL, 12000.0000);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Visa Unibanco', 4, 1, 20, NULL, 3000.0000);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Citibank', 1, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('*Estimate*', 6, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Divida Elie', 5, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('ILE Loan', 5, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Fundos Camelomanco', 3, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Fundos Elie', 3, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Fundos Itau', 3, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Fundos Real', 3, 1, 20, NULL, NULL);
INSERT INTO `Account` (`name`, `account_type`, `financial_institution`, `currency`, `ofx_acct_id`, `acct_limit`) VALUES ('Fundos Sandra', 3, 1, 20, NULL, NULL);
