INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (1, NULL, 'Bonus');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (2, NULL, 'Cheque recebido');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (3, NULL, 'depósito');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (4, 3, 'cheque');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (5, 3, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (6, NULL, 'Div Income');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (7, NULL, 'Dolar');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (8, NULL, 'Fanta');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (9, NULL, 'Finance Charge');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (10, NULL, 'Gift Received');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (11, NULL, 'Gr Sales');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (12, NULL, 'Impostos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (13, 12, 'IR');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (14, 12, 'Restituição');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (15, 12, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (16, NULL, 'Interest Inc');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (17, NULL, 'Invest Inc');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (18, NULL, 'Loan');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (19, NULL, 'Net Salary');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (20, NULL, 'Other Inc');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (21, NULL, 'Other Inc, Bus');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (22, NULL, 'Reembolso');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (23, NULL, 'Rendimento de investimento');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (24, 23, 'Juros');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (25, 23, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (26, NULL, 'Resgate');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (27, 26, 'DI 90');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (28, 26, 'RF 90');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (29, 26, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (30, NULL, 'Salários e ordenado');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (31, 30, '13º salário');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (32, 30, 'bonus 2006');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (33, 30, 'Férias');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (34, 30, 'Pagamento indevido');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (35, 30, 'Pagamento líquido');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (36, 30, 'Superação');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (37, 30, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (38, NULL, 'Tax Refund');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (39, NULL, 'Unemployment Inc');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (40, NULL, 'Venda');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (41, 40, 'livro');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (42, 40, 'Misc');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (43, 40, 'quadrinhos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (44, 40, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (45, NULL, '_DepCareContrib');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (46, NULL, '_DivInc');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (47, NULL, '_DivIncTaxFree');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (48, NULL, '_EmpStkOptInc');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (49, NULL, '_EmpStkOptIncSpouse');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (50, NULL, '_ESPP Self Income');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (51, NULL, '_ESPP Spouse Income');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (52, NULL, '_FlexContrib');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (53, NULL, '_IntInc');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (54, NULL, '_IntIncTaxFree');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (55, NULL, '_LT CapGnDst');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (56, NULL, '_MT CapGnDst');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (57, NULL, '_RlzdGain');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (58, NULL, '_ST CapGnDst');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (59, NULL, '_UnrlzdGain');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (60, NULL, 'Academia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (61, 60, 'Exame Médico');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (62, 60, 'Mensalidade');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (63, 60, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (64, NULL, 'Alimentação');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (65, 64, 'Bar');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (66, 64, 'Bombonière');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (67, 64, 'Cafeteria');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (68, 64, 'Doces');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (69, 64, 'Feira');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (70, 64, 'Lanchonete');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (71, 64, 'Padaria');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (72, 64, 'Restaurantes');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (73, 64, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (74, NULL, 'Aluguel');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (75, NULL, 'aniversário');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (76, 75, 'Cleia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (77, 75, 'Lourdes');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (78, 75, 'Renato Dantas');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (79, 75, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (80, NULL, 'Apartamento');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (81, 80, 'antes das chaves');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (82, 80, 'Chaves');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (83, 80, 'contratual');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (84, 80, 'financiamento');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (85, 80, 'Reforma');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (86, 85, 'banheiros');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (87, 85, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (88, 80, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (89, NULL, 'Aplicação');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (90, NULL, 'arquitetura');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (91, 90, 'abajur');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (92, 90, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (93, NULL, 'Automóvel');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (94, 93, 'Combustível');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (95, 93, 'Compra');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (96, 93, 'Despachante');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (97, 93, 'Estacionamento');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (98, 93, 'Inspeção Veicular');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (99, 93, 'Lavagem');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (100, 93, 'Licenciamento');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (101, 93, 'Manutenção');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (102, 93, 'Multa');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (103, 93, 'Seguro');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (104, 93, 'Som');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (105, 93, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (106, NULL, 'Banco Itaú');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (107, NULL, 'Bank Charge');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (108, NULL, 'Bebê');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (109, 108, 'Beni');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (110, 108, 'Leo ou Helena');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (111, 108, 'Tali');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (112, 111, 'alimentação');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (113, 111, 'aniversário');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (114, 111, 'brinquedos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (115, 111, 'cabelereiro');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (116, 111, 'fotos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (117, 111, 'fraldas');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (118, 111, 'Livro');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (119, 111, 'mamadeiras e chupetas');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (120, 111, 'passeio');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (121, 111, 'pomadas');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (122, 111, 'quarto');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (123, 111, 'roupas');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (124, 111, 'sapato');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (125, 111, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (126, 108, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (127, NULL, 'Cancelado');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (128, NULL, 'Carteirinha');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (129, 128, 'Fabio');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (130, 128, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (131, NULL, 'cartão de crédito');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (132, 131, 'anuidade');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (133, 131, 'pagamento fatura');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (134, 131, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (135, NULL, 'Casa');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (136, 135, 'Babá');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (137, 135, 'Cabos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (138, 135, 'Empregada');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (139, 135, 'enxoval');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (140, 135, 'Floricultura');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (141, 135, 'Higiene');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (142, 135, 'Pilhas');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (143, 135, 'quarto');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (144, 135, 'Supermercado');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (145, 135, 'utensilios Cozinha');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (146, 135, 'VideoGame');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (147, 135, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (148, NULL, 'Casamento');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (149, 148, 'Bolo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (150, 148, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (151, NULL, 'Cash');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (152, NULL, 'Commission');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (153, NULL, 'Computador');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (154, 153, 'Cartão SD');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (155, 153, 'Cd\\''s');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (156, 153, 'DVDs');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (157, 153, 'HD');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (158, 153, 'Impressora');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (159, 153, 'Monitor');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (160, 153, 'Mouse');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (161, 153, 'Scanner');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (162, 153, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (163, NULL, 'Computer');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (164, NULL, 'Conserto');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (165, NULL, 'Cosméticos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (166, NULL, 'Despesas pessoais');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (167, 166, 'acessórios');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (168, 166, 'eletro');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (169, 166, 'Jóia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (170, 166, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (171, NULL, 'Dining');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (172, NULL, 'Diversos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (173, 172, 'balas');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (174, 172, 'bijuteria');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (175, 172, 'dinheiro para aplicação');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (176, 172, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (177, NULL, 'Doações de caridade');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (178, 177, 'Cleia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (179, 177, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (180, NULL, 'Education');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (181, NULL, 'Educação');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (182, 181, 'Ballet');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (183, 181, 'curso');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (184, 181, 'Inglês');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (185, 181, 'Uniforme');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (186, 181, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (187, NULL, 'Eletrônicos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (188, 187, 'telefone');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (189, 187, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (190, NULL, 'Employee Benefit, Business');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (191, NULL, 'Empréstimo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (192, 191, 'Alain');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (193, 191, 'Anderson');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (194, 191, 'Cheng');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (195, 191, 'Cooperativa');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (196, 191, 'devolução');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (197, 191, 'Kluk');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (198, 191, 'Lourdes');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (199, 191, 'Mami');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (200, 191, 'Mona');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (201, 191, 'Papi');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (202, 191, 'Silvia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (203, 191, 'Terry');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (204, 191, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (205, NULL, 'Entertainment');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (206, NULL, 'Estética');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (207, 206, 'chapinha');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (208, 206, 'corte');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (209, 206, 'creme p-cabelo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (210, 206, 'depilação');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (211, 206, 'escova');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (212, 206, 'limpeza de pele');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (213, 206, 'manicure');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (214, 206, 'massagem');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (215, 206, 'olhos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (216, 206, 'podologo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (217, 206, 'vários');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (218, 206, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (219, NULL, 'Farmácia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (220, 219, 'colirio');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (221, 219, 'remédio');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (222, 219, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (223, NULL, 'festa');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (224, 223, 'G5');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (225, 223, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (226, NULL, 'Filhos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (227, NULL, 'Filmadora');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (228, 227, 'Bateria');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (229, 227, 'fitas');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (230, 227, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (231, NULL, 'Férias');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (232, 231, 'Viagens');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (233, 231, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (234, NULL, 'Gadget');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (235, NULL, 'Gifts Given');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (236, NULL, 'Ginástica');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (237, 236, 'Yoga');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (238, 236, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (239, NULL, 'Household');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (240, NULL, 'ILE Eco Life');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (241, 240, 'condominio');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (242, 240, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (243, NULL, 'Imposto');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (244, 243, 'CSLL');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (245, 243, 'GPS');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (246, 243, 'IPTU');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (247, 243, 'IRPF');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (248, 243, 'IRPJ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (249, 243, 'IRRF');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (250, 243, 'ISS');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (251, 243, 'Sindicato');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (252, 243, 'TFE');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (253, 243, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (254, NULL, 'Judaísmo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (255, 254, 'Mezuza');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (256, 254, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (257, NULL, 'Lazer');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (258, 257, 'Cinema e locação de vídeo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (259, 257, 'Dança');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (260, 257, 'Diversão');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (261, 257, 'DVD');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (262, 257, 'Festa');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (263, 257, 'Fitas e CDs');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (264, 257, 'Livros e revistas');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (265, 257, 'Musical');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (266, 257, 'passeio');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (267, 257, 'Recreação');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (268, 257, 'Restaurantes e Lanchonetes');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (269, 257, 'Teatro');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (270, 257, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (271, NULL, 'Legal-Prof Fees');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (272, NULL, 'Licenses and Permits');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (273, NULL, 'Meals & Entertn');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (274, NULL, 'Medical');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (275, 274, 'Dentist');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (276, 274, 'Doctor');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (277, 274, 'Medicine');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (278, 274, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (279, NULL, 'Misc');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (280, NULL, 'Moeda Estrangeira');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (281, 280, 'dólar');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (282, 280, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (283, NULL, 'Mortgage Interest, Business');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (284, NULL, 'Not Sure, Biz');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (285, NULL, 'Not Sure, Rental');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (286, NULL, 'Objetos da casa');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (287, 286, 'armário');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (288, 286, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (289, NULL, 'Outros rendimentos');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (290, 289, 'Eilat');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (291, 289, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (292, NULL, 'Papelaria');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (293, NULL, 'Personal Care');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (294, NULL, 'Postage and Delivery');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (295, NULL, 'Presentes');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (296, 295, 'Abril');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (297, 295, 'Adilson');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (298, 295, 'Alain');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (299, 295, 'Alexandre');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (300, 295, 'Anderson Portela');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (301, 295, 'Andrea e Michelle');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (302, 295, 'Arthur');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (303, 295, 'Auro');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (304, 295, 'Carol e Dotan');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (305, 295, 'casamento');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (306, 295, 'Cecilia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (307, 295, 'Cleia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (308, 295, 'Coca');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (309, 295, 'Daniel');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (310, 295, 'Dayvi');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (311, 295, 'Eduardo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (312, 295, 'Fabio');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (313, 295, 'Fanta');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (314, 295, 'Francisco Anselmo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (315, 295, 'Gabi');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (316, 295, 'Gabriel');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (317, 295, 'Gladis e Coca');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (318, 295, 'Jairo e Raquel');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (319, 295, 'Junior');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (320, 295, 'Lourdes Oliveira');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (321, 295, 'Luana');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (322, 295, 'Mami');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (323, 295, 'Marcelo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (324, 295, 'Mona');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (325, 295, 'Monica Viotto');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (326, 295, 'Papi');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (327, 295, 'Raquel');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (328, 295, 'Regina Wilner');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (329, 295, 'Sandra');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (330, 295, 'Silvia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (331, 295, 'Sofia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (332, 295, 'Stefanie');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (333, 295, 'Tali');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (334, 295, 'Terry');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (335, 295, 'Thaís');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (336, 295, 'Varios');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (337, 295, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (338, NULL, 'Previdencia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (339, 338, 'Educação');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (340, 338, 'Previdencia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (341, 338, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (342, NULL, 'Printing and Reproduction');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (343, NULL, 'Recreation');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (344, NULL, 'Retirada de dinheiro');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (345, NULL, 'Returns');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (346, NULL, 'Roupas');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (347, 346, 'biquini');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (348, 346, 'blaser');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (349, 346, 'blusa');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (350, 346, 'bodies');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (351, 346, 'bolsa');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (352, 346, 'bota');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (353, 346, 'cachecol');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (354, 346, 'calça');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (355, 346, 'camiseta');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (356, 346, 'jaqueta');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (357, 346, 'jeans');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (358, 346, 'Lavanderia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (359, 346, 'lingerie');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (360, 346, 'malha');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (361, 346, 'meia calça');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (362, 346, 'meias');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (363, 346, 'pijama');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (364, 346, 'quilot');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (365, 346, 'sapato');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (366, 346, 'Tali');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (367, 346, 'terninho');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (368, 346, 'terno');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (369, 346, 'vestido');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (370, 346, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (371, 346, 'óculos escuros');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (372, NULL, 'Saúde');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (373, 372, 'Acupuntura');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (374, 372, 'Convênio');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (375, 372, 'Dentista');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (376, 372, 'Dermatologista');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (377, 372, 'Dieta');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (378, 372, 'Endocrinologista');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (379, 372, 'Fonoaudiologia');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (380, 372, 'Remédios');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (381, 372, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (382, NULL, 'Subscriptions');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (383, NULL, 'Tax, Business');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (384, 383, 'Fed');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (385, 383, 'Local');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (386, 383, 'Property');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (387, 383, 'State');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (388, 383, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (389, NULL, 'Taxas bancárias');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (390, 389, 'canc. Resgate');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (391, 389, 'cartao Real');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (392, 389, 'ch inf a $ 20');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (393, 389, 'ch inf a $ 25');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (394, 389, 'ch inf a $ 30');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (395, 389, 'conta negativa');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (396, 389, 'CPMF');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (397, 389, 'DOC');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (398, 389, 'formula 1');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (399, 389, 'IOC');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (400, 389, 'IOF');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (401, 389, 'retirada');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (402, 389, 'Saque sobre cheque');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (403, 389, 'talão cheques');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (404, 389, 'TED');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (405, 389, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (406, NULL, 'Utilidades');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (407, 406, 'Celular');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (408, 407, 'Claro');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (409, 407, 'TIM');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (410, 407, 'VIVO');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (411, 407, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (412, 406, 'Clube');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (413, 406, 'Contribuição Sindical');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (414, 406, 'CRA');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (415, 406, 'Domíno De Internet');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (416, 406, 'Eletropaulo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (417, 406, 'Gás');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (418, 406, 'Internet');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (419, 406, 'Sabesp');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (420, 406, 'Telefone');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (421, 406, 'TV a cabo');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (422, 406, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (423, NULL, 'Vacation');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (424, 423, 'Lodging');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (425, 423, 'Travel');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (426, 423, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (427, NULL, 'Viagem');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (428, 427, 'Maresias');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (429, 427, 'Orlando');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (430, 427, 'Pauba');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (431, 427, 'Piracicaba');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (432, 427, 'Ubatuba');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (433, 427, 'Visconde de Mauá');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (434, 427, 'ZZZZZ');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (435, NULL, 'Wages');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (436, NULL, '_Accrued Int');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (437, NULL, '_IntExp');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (438, NULL, '_MileageBus');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (439, NULL, '_MileageChrity');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (440, NULL, '_MileageMedl');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (441, NULL, '_MileageOthr');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (442, NULL, '_MileageRentl');
INSERT INTO `Category` (`id`, `parent`, `name`) VALUES (443, NULL, '_MileageUnreimBus');
