INSERT INTO FinancialInstitution (name) VALUES ('UNKNOWN');
INSERT INTO AccountType (name,ofx_type) VALUES ('Checking','CHECKING');
INSERT INTO AccountType (name,ofx_type) VALUES ('Savings','SAVINGS');
INSERT INTO AccountType (name,ofx_type) VALUES ('Investment','MONEYMRKT');
INSERT INTO AccountType (name,ofx_type) VALUES ('Credit Card','CREDITLINE');
INSERT INTO AccountType (name) VALUES ('Liability');
INSERT INTO AccountType (name) VALUES ('Asset');
INSERT INTO Currency (symbol,name) VALUES ('AED','United Arab Emirates dirham');
INSERT INTO Currency (symbol,name) VALUES ('AFN','Afghan afghani');
INSERT INTO Currency (symbol,name) VALUES ('ALL','Albanian lek');
INSERT INTO Currency (symbol,name) VALUES ('AMD','Armenian dram');
INSERT INTO Currency (symbol,name) VALUES ('ANG','Netherlands Antillean guilder');
INSERT INTO Currency (symbol,name) VALUES ('AOA','Angolan kwanza');
INSERT INTO Currency (symbol,name) VALUES ('ARS','Argentine peso');
INSERT INTO Currency (symbol,name) VALUES ('AUD','Australian dollar');
INSERT INTO Currency (symbol,name) VALUES ('AWG','Aruban florin');
INSERT INTO Currency (symbol,name) VALUES ('AZN','Azerbaijani manat');
INSERT INTO Currency (symbol,name) VALUES ('BAM','Bosnia and Herzegovina convertible mark');
INSERT INTO Currency (symbol,name) VALUES ('BBD','Barbados dollar');
INSERT INTO Currency (symbol,name) VALUES ('BDT','Bangladeshi taka');
INSERT INTO Currency (symbol,name) VALUES ('BGN','Bulgarian lev');
INSERT INTO Currency (symbol,name) VALUES ('BHD','Bahraini dinar');
INSERT INTO Currency (symbol,name) VALUES ('BIF','Burundian franc');
INSERT INTO Currency (symbol,name) VALUES ('BMD','Bermudian dollar');
INSERT INTO Currency (symbol,name) VALUES ('BND','Brunei dollar');
INSERT INTO Currency (symbol,name) VALUES ('BOB','Boliviano');
INSERT INTO Currency (symbol,name) VALUES ('BRL','Brazilian real');
INSERT INTO Currency (symbol,name) VALUES ('BSD','Bahamian dollar');
INSERT INTO Currency (symbol,name) VALUES ('BTN','Bhutanese ngultrum');
INSERT INTO Currency (symbol,name) VALUES ('BWP','Botswana pula');
INSERT INTO Currency (symbol,name) VALUES ('BYR','Belarusian ruble');
INSERT INTO Currency (symbol,name) VALUES ('BZD','Belize dollar');
INSERT INTO Currency (symbol,name) VALUES ('CAD','Canadian dollar');
INSERT INTO Currency (symbol,name) VALUES ('CDF','Congolese franc');
INSERT INTO Currency (symbol,name) VALUES ('CHF','Swiss franc');
INSERT INTO Currency (symbol,name) VALUES ('CLP','Chilean peso');
INSERT INTO Currency (symbol,name) VALUES ('CNY','Chinese yuan');
INSERT INTO Currency (symbol,name) VALUES ('COP','Colombian peso');
INSERT INTO Currency (symbol,name) VALUES ('CRC','Costa Rican colon');
INSERT INTO Currency (symbol,name) VALUES ('CUP','Cuban peso');
INSERT INTO Currency (symbol,name) VALUES ('CVE','Cape Verde escudo');
INSERT INTO Currency (symbol,name) VALUES ('CYP','Cypriot pound');
INSERT INTO Currency (symbol,name) VALUES ('CZK','Czech koruna');
INSERT INTO Currency (symbol,name) VALUES ('DJF','Djiboutian franc');
INSERT INTO Currency (symbol,name) VALUES ('DKK','Danish krone');
INSERT INTO Currency (symbol,name) VALUES ('DOP','Dominican peso');
INSERT INTO Currency (symbol,name) VALUES ('DZD','Algerian dinar');
INSERT INTO Currency (symbol,name) VALUES ('EEK','Estonian kroon');
INSERT INTO Currency (symbol,name) VALUES ('EGP','Egyptian pound');
INSERT INTO Currency (symbol,name) VALUES ('ERN','Eritrean nakfa');
INSERT INTO Currency (symbol,name) VALUES ('ETB','Ethiopian birr');
INSERT INTO Currency (symbol,name) VALUES ('EUR','Euro');
INSERT INTO Currency (symbol,name) VALUES ('FJD','Fiji dollar');
INSERT INTO Currency (symbol,name) VALUES ('FKP','Falkland Islands pound');
INSERT INTO Currency (symbol,name) VALUES ('GBP','Pound sterling');
INSERT INTO Currency (symbol,name) VALUES ('GEL','Georgian lari');
INSERT INTO Currency (symbol,name) VALUES ('GGP','Guernsey pound');
INSERT INTO Currency (symbol,name) VALUES ('GHS','Ghanaian cedi');
INSERT INTO Currency (symbol,name) VALUES ('GIP','Gibraltar pound');
INSERT INTO Currency (symbol,name) VALUES ('GMD','Gambian dalasi');
INSERT INTO Currency (symbol,name) VALUES ('GNF','Guinean franc');
INSERT INTO Currency (symbol,name) VALUES ('GTQ','Guatemalan quetzal');
INSERT INTO Currency (symbol,name) VALUES ('GYD','Guyanese dollar');
INSERT INTO Currency (symbol,name) VALUES ('HKD','Hong Kong dollar');
INSERT INTO Currency (symbol,name) VALUES ('HNL','Honduran lempira');
INSERT INTO Currency (symbol,name) VALUES ('HRK','Croatian kuna');
INSERT INTO Currency (symbol,name) VALUES ('HTG','Haitian gourde');
INSERT INTO Currency (symbol,name) VALUES ('HUF','Hungarian forint');
INSERT INTO Currency (symbol,name) VALUES ('IDR','Indonesian rupiah');
INSERT INTO Currency (symbol,name) VALUES ('ILS','Israeli new sheqel');
INSERT INTO Currency (symbol,name) VALUES ('IMP','Isle of Man pound');
INSERT INTO Currency (symbol,name) VALUES ('INR','Indian rupee');
INSERT INTO Currency (symbol,name) VALUES ('IQD','Iraqi dinar');
INSERT INTO Currency (symbol,name) VALUES ('IRR','Iranian rial');
INSERT INTO Currency (symbol,name) VALUES ('ISK','Icelandic króna');
INSERT INTO Currency (symbol,name) VALUES ('JEP','Jersey pound');
INSERT INTO Currency (symbol,name) VALUES ('JMD','Jamaican dollar');
INSERT INTO Currency (symbol,name) VALUES ('JOD','Jordanian dinar');
INSERT INTO Currency (symbol,name) VALUES ('JPY','Japanese yen');
INSERT INTO Currency (symbol,name) VALUES ('KES','Kenyan shilling');
INSERT INTO Currency (symbol,name) VALUES ('KGS','Kyrgyzstani som');
INSERT INTO Currency (symbol,name) VALUES ('KHR','Cambodian riel');
INSERT INTO Currency (symbol,name) VALUES ('KMF','Comoro franc');
INSERT INTO Currency (symbol,name) VALUES ('KPW','North Korean won');
INSERT INTO Currency (symbol,name) VALUES ('KRW','South Korean won');
INSERT INTO Currency (symbol,name) VALUES ('KWD','Kuwaiti dinar');
INSERT INTO Currency (symbol,name) VALUES ('KYD','Cayman Islands dollar');
INSERT INTO Currency (symbol,name) VALUES ('KZT','Kazakhstani tenge');
INSERT INTO Currency (symbol,name) VALUES ('LAK','Lao kip');
INSERT INTO Currency (symbol,name) VALUES ('LBP','Lebanese pound');
INSERT INTO Currency (symbol,name) VALUES ('LKR','Sri Lanka rupee');
INSERT INTO Currency (symbol,name) VALUES ('LRD','Liberian dollar');
INSERT INTO Currency (symbol,name) VALUES ('LSL','Lesotho loti');
INSERT INTO Currency (symbol,name) VALUES ('LTL','Lithuanian litas');
INSERT INTO Currency (symbol,name) VALUES ('LVL','Latvian lats');
INSERT INTO Currency (symbol,name) VALUES ('LYD','Libyan dinar');
INSERT INTO Currency (symbol,name) VALUES ('MAD','Moroccan dirham');
INSERT INTO Currency (symbol,name) VALUES ('MDL','Moldovan leu');
INSERT INTO Currency (symbol,name) VALUES ('MGA','Malagasy ariary');
INSERT INTO Currency (symbol,name) VALUES ('MKD','Macedonian denar');
INSERT INTO Currency (symbol,name) VALUES ('MMK','Myanma kyat');
INSERT INTO Currency (symbol,name) VALUES ('MNT','Mongolian tugrik');
INSERT INTO Currency (symbol,name) VALUES ('MOP','Macanese pataca');
INSERT INTO Currency (symbol,name) VALUES ('MRO','Mauritanian ouguiya');
INSERT INTO Currency (symbol,name) VALUES ('MTL','Maltese lira');
INSERT INTO Currency (symbol,name) VALUES ('MUR','Mauritian rupee');
INSERT INTO Currency (symbol,name) VALUES ('MVR','Maldivian rufiyaa');
INSERT INTO Currency (symbol,name) VALUES ('MWK','Malawian kwacha');
INSERT INTO Currency (symbol,name) VALUES ('MXN','Mexican peso');
INSERT INTO Currency (symbol,name) VALUES ('MYR','Malaysian ringgit');
INSERT INTO Currency (symbol,name) VALUES ('MZN','Mozambican metical');
INSERT INTO Currency (symbol,name) VALUES ('NAD','Namibian dollar');
INSERT INTO Currency (symbol,name) VALUES ('NGN','Nigerian naira');
INSERT INTO Currency (symbol,name) VALUES ('NIO','Cordoba oro');
INSERT INTO Currency (symbol,name) VALUES ('NOK','Norwegian krone');
INSERT INTO Currency (symbol,name) VALUES ('NPR','Nepalese rupee');
INSERT INTO Currency (symbol,name) VALUES ('NZD','New Zealand dollar');
INSERT INTO Currency (symbol,name) VALUES ('OMR','Omani rial');
INSERT INTO Currency (symbol,name) VALUES ('PAB','Panamanian balboa');
INSERT INTO Currency (symbol,name) VALUES ('PEN','Peruvian nuevo sol');
INSERT INTO Currency (symbol,name) VALUES ('PGK','Papua New Guinean kina');
INSERT INTO Currency (symbol,name) VALUES ('PHP','Philippine peso');
INSERT INTO Currency (symbol,name) VALUES ('PKR','Pakistani rupee');
INSERT INTO Currency (symbol,name) VALUES ('PLN','Polish zloty');
INSERT INTO Currency (symbol,name) VALUES ('PYG','Paraguayan guaraní');
INSERT INTO Currency (symbol,name) VALUES ('QAR','Qatari rial');
INSERT INTO Currency (symbol,name) VALUES ('RON','Romanian new leu');
INSERT INTO Currency (symbol,name) VALUES ('RSD','Serbian dinar');
INSERT INTO Currency (symbol,name) VALUES ('RUB','Russian rouble');
INSERT INTO Currency (symbol,name) VALUES ('RWF','Rwandan franc');
INSERT INTO Currency (symbol,name) VALUES ('SAR','Saudi riyal');
INSERT INTO Currency (symbol,name) VALUES ('SBD','Solomon Islands dollar');
INSERT INTO Currency (symbol,name) VALUES ('SCR','Seychelles rupee');
INSERT INTO Currency (symbol,name) VALUES ('SDG','Sudanese pound');
INSERT INTO Currency (symbol,name) VALUES ('SEK','Swedish krona/kronor');
INSERT INTO Currency (symbol,name) VALUES ('SGD','Singapore dollar');
INSERT INTO Currency (symbol,name) VALUES ('SHP','Saint Helena pound');
INSERT INTO Currency (symbol,name) VALUES ('SIT','Slovenian Tolar');
INSERT INTO Currency (symbol,name) VALUES ('SKK','Slovak koruna');
INSERT INTO Currency (symbol,name) VALUES ('SLL','Sierra Leonean leone');
INSERT INTO Currency (symbol,name) VALUES ('SOS','Somali shilling');
INSERT INTO Currency (symbol,name) VALUES ('SRD','Surinamese dollar');
INSERT INTO Currency (symbol,name) VALUES ('STD','São Tomé and Príncipe dobra');
INSERT INTO Currency (symbol,name) VALUES ('SVC','Salvadoran colón');
INSERT INTO Currency (symbol,name) VALUES ('SYP','Syrian pound');
INSERT INTO Currency (symbol,name) VALUES ('SZL','Lilangeni');
INSERT INTO Currency (symbol,name) VALUES ('THB','Thai baht');
INSERT INTO Currency (symbol,name) VALUES ('TJS','Tajikistani somoni');
INSERT INTO Currency (symbol,name) VALUES ('TMT','Turkmenistani manat');
INSERT INTO Currency (symbol,name) VALUES ('TND','Tunisian dinar');
INSERT INTO Currency (symbol,name) VALUES ('TOP','Tongan pa`anga');
INSERT INTO Currency (symbol,name) VALUES ('TRY','Turkish lira');
INSERT INTO Currency (symbol,name) VALUES ('TTD','Trinidad and Tobago dollar');
INSERT INTO Currency (symbol,name) VALUES ('TVD','Tuvalu dollar');
INSERT INTO Currency (symbol,name) VALUES ('TWD','New Taiwan dollar');
INSERT INTO Currency (symbol,name) VALUES ('TZS','Tanzanian shilling');
INSERT INTO Currency (symbol,name) VALUES ('UAH','Ukrainian hryvnia');
INSERT INTO Currency (symbol,name) VALUES ('UGX','Ugandan shilling');
INSERT INTO Currency (symbol,name) VALUES ('USD','United States dollar');
INSERT INTO Currency (symbol,name) VALUES ('UYU','Uruguayan peso');
INSERT INTO Currency (symbol,name) VALUES ('UZS','Uzbekistan som');
INSERT INTO Currency (symbol,name) VALUES ('VEF','Venezuelan bolívar fuerte');
INSERT INTO Currency (symbol,name) VALUES ('VND','Vietnamese dông');
INSERT INTO Currency (symbol,name) VALUES ('VUV','Vanuatu vatu');
INSERT INTO Currency (symbol,name) VALUES ('WST','Samoan tala');
INSERT INTO Currency (symbol,name) VALUES ('XAF','CFA franc BEAC');
INSERT INTO Currency (symbol,name) VALUES ('XAG','Silver (one troy ounce)');
INSERT INTO Currency (symbol,name) VALUES ('XAU','Gold (one troy ounce)');
INSERT INTO Currency (symbol,name) VALUES ('XCD','East Caribbean dollar');
INSERT INTO Currency (symbol,name) VALUES ('XDR','Special Drawing Rights');
INSERT INTO Currency (symbol,name) VALUES ('XOF','CFA Franc BCEAO');
INSERT INTO Currency (symbol,name) VALUES ('XPD','Palladium (one troy ounce)');
INSERT INTO Currency (symbol,name) VALUES ('XPF','CFP franc');
INSERT INTO Currency (symbol,name) VALUES ('XPT','Platinum (one troy ounce)');
INSERT INTO Currency (symbol,name) VALUES ('XTS','Code reserved for testing purposes');
INSERT INTO Currency (symbol,name) VALUES ('XXX','No currency');
INSERT INTO Currency (symbol,name) VALUES ('YER','Yemeni rial');
INSERT INTO Currency (symbol,name) VALUES ('ZAR','South African rand');
INSERT INTO Currency (symbol,name) VALUES ('ZMK','Zambian kwacha');
INSERT INTO Currency (symbol,name) VALUES ('ZWL','Zimbabwe dollar');